language: crystal
# services:
#   - postgresql
# before_script:
#   - psql -c 'create database hornet_test;' -U postgres
env:
  - HORNET_ENV=test
# - HORNET_DB_URL=postgres://postgres@localhost:5432/hornet_test
script:
  - crystal tool format --check src spec db
  - crystal spec
  - shards build --no-codegen
