version: '3'

services:
  bot:
    build: .
    depends_on:
      - redis
  redis:
    image: redis:3.2
    command: redis-server --appendonly yes
    volumes:
      - ./.redis:/data
    ports:
      - 6379:6379
